### ISSUE TITLE
Add missing emotes to ClanMod

### ISSUE THREAD

**Issue by ineedblood** [erfg12/clanmod-jka#10]
ClanMod has missing emotes from JA+/JA++,  WIP

**Comment by erfg12** [comment]
As long as they aren't custom animations. Custom animations will show as a "T" null animation if they don't have the client plugin, which I want to avoid.

**Comment by ineedblood** [comment]
Hmm... The emotes I mean are the ones included in the anims of the game such as 

BOTH_FORCE_DRAIN_GRABBED

which is the one you get when you get force drained on SP, as far as I know they are not custom and they come with the game unless I am missing something

**Comment by erfg12** [comment]
Sure, that's good. If you're using the animations already present in the source, that works.

**Comment by ineedblood** [comment]
Sure thing, I want to avoid doing any client-side requirements because it's a pain to handle(such as japlus special attacks), so for the added emotes I will stick to source animations

**Comment by ineedblood** [comment]
@erfg12 how are new emotes bitvalues calculated?

```C
typedef enum{    E_MYHEAD = 0,    E_COWER,    E_SMACK,    E_ENRAGED,    E_VICTORY1,    E_VICTORY2,    E_VICTORY3,    E_SWIRL,
    E_DANCE1,    E_DANCE2,    E_DANCE3,    E_SIT1, //Punch    E_SIT2, //Intimidate    E_SIT3, //Slash    E_SIT4, //Sit    E_SIT5, //Sit2    E_KNEEL1,    E_KNEEL2,    E_KNEEL3,    E_SLEEP,    E_BREAKDANCE,    E_CHEER,    E_SURRENDER,    E_HEADSHAKE, //v1.08 BEGINS    E_HEADNOD,    E_ATEASE,    E_COMEON,    E_KISS,    E_HUG,    E_HARLEM, // Do the harlem shake    E_WAIT,    E_HELLO,    E_HEAL} emote_type_t;
```

This is my current list, added 4 emotes after the current list, is there any formula?

**Comment by erfg12** [comment]
E_HUT = 268435456
E_HARLEM = 536870912 (268435456*2)
power of 2.
