### ISSUE TITLE
Missing amstatus command 

### ISSUE THREAD

**Issue by ineedblood** [erfg12/clanmod-jka#13]
Amstatus command provides a list of the current players, nicknames and ip addresses , also client numbers.

seems to be missing in clanmod

**Comment by ineedblood** [comment]
This is the end result of the command 
![image](https://user-images.githubusercontent.com/8579024/49176428-1f6af480-f34b-11e8-88f4-39035700c559.png)

**Comment by erfg12** [comment]
Modify `whoip` to add any features needed. Add /amstatus as an optional command:

    else if ((Q_stricmp(cmd, "whoip") == 0) || (Q_stricmp(cmd, "amwhoip") == 0)) 

change to:

    else if ((Q_stricmp(cmd, "whoip") == 0) || (Q_stricmp(cmd, "amwhoip") == 0) || (Q_stricmp(cmd, "amstatus") == 0))
